-- ============================================================
-- 024 — Customer lifecycle extension + Swarm Summary persistence
-- ============================================================
-- 1. Extend customers.lifecycle_stage CHECK to allow 'sold' and 'lost'
--    so the customer detail panel can record won/dead outcomes.
-- 2. Add swarm_summary columns so the AI-generated one-paragraph
--    profile summary persists across sessions.
-- ============================================================

-- Drop existing CHECK and re-add with the new values.
ALTER TABLE customers
  DROP CONSTRAINT IF EXISTS customers_lifecycle_stage_check;

ALTER TABLE customers
  ADD CONSTRAINT customers_lifecycle_stage_check
  CHECK (lifecycle_stage IN (
    'prospect','active','at_risk','lapsed','vip','sold','lost'
  ));

-- Persisted Swarm Summary (AI-generated one-paragraph profile).
ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS swarm_summary       TEXT,
  ADD COLUMN IF NOT EXISTS swarm_summary_at    TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS swarm_summary_model TEXT;

COMMENT ON COLUMN customers.swarm_summary       IS 'One-paragraph customer profile generated by the AI swarm.';
COMMENT ON COLUMN customers.swarm_summary_at    IS 'When the summary was last regenerated.';
COMMENT ON COLUMN customers.swarm_summary_model IS 'Anthropic model id used for the summary.';

-- Helpful index for any future "stale summary" reports.
CREATE INDEX IF NOT EXISTS idx_customers_swarm_summary_at
  ON customers (dealership_id, swarm_summary_at DESC NULLS LAST);
